# Generated by Django 3.2.8 on 2021-10-14 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('date_created', models.DateField()),
                ('membership_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
