# Generated by Django 3.2.8 on 2021-10-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_membership_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='membership_plan',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
