# Generated by Django 3.2.8 on 2021-10-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211014_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_plan',
            new_name='course_plan',
        ),
    ]
