# Generated by Django 3.2.4 on 2021-10-15 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_membership_plan_membership_course_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_plan',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
