# Generated by Django 3.2.4 on 2021-10-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211015_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_plan',
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('membership_type', models.OneToOneField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
