# Generated by Django 3.2.8 on 2021-11-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211020_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.membership'),
        ),
    ]
