# Generated by Django 3.2.8 on 2021-11-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('courses', '0010_auto_20211101_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
