# Generated by Django 3.2.8 on 2021-11-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('courses', '0011_auto_20211101_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_membership',
        ),
        migrations.AddField(
            model_name='course',
            name='Membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
    ]
