# Generated by Django 3.2.8 on 2021-11-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20211101_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Membership_type',
            new_name='type',
        ),
    ]
